Major rewrite of code generation and source mapping
kolint/kolint pull request #226
Opened 2021-05-13 15:59 UTC by maskmaster

* Optimize the compilation flow to take advantage of typescript's incremental parsing.
* Change to append-only when generating code and inferring types. Only standard typescript APIs used.
* Update grammar and code to new syntax for managing binding contexts (ko-import, ko-context and ko-viewmodel)
* Handle multiple named imports
* Add "typeof" support for viewmodel references
* Add support to modify the current context. Type hints make it possible to assert "magical" binding handlers where it is not possible to infer the type. E.g. Durandal's binding handler "Widget".
* Add support for analyzing multiple files at a time
* Move emit responsibilities to SourceBuilder
* Add revision control in the SourcBuilder to support the incremental updates (enables the generational source mapping)
* Filter out properties that are not valid variable names. (work around until we can support all possible property names)

* Use latest released typescript
* Upgrade packages and update code accordingly.

* Improved error reporting.
* Add support for $index and $parentContext to binding context types.
* Keep better track of diagnostic's originating file

* Fix typing for 'foreach' bindings (handle the 'as' property)
* Fix source map references for all transformed identifiers
* Fix diagnostic output with source mapped positions.

Fixes #147, #82, #75, #17

2021-05-13 16:17 UTC, tscpp requested changes

2021-05-13 16:17 UTC, tscpp commented on demo/resources/bindinghandler.ts
>  type koko<Value = string[]> = {
Rename to a binding handler name that makes sense. Maybe `test`?

2021-05-13 16:17 UTC, tscpp commented on lib/resources/context.d.ts
> +import 'knockout'
What does this do? I think these kinds of imports are not effecting the types.

2021-05-13 16:17 UTC, tscpp commented on lib/resources/context.d.ts
>  			'\'as\' must be a string literal' :
Cannot the generic type `Key` extend `string`. If so the `'\'as\' must be a string literal'` is unnecessary, because it will `never` happen.

2021-05-13 16:17 UTC, tscpp commented on spec/src/spec.ts
> +	// ],
Is this needed anymore?

2021-05-13 16:17 UTC, tscpp commented on spec/src/spec.ts
> +// const emitTestString = '<!-- ko-viewmodel: import default from \'nothing2\' -->\n<img data-bind="test: undefined">\n<img data-bind="text: notdefined">'
Is this needed anymore?

2021-05-13 16:17 UTC, tscpp commented on src/cli/cli.ts
> +		process.exit(-1)
Why -1?

2021-05-13 16:17 UTC, tscpp commented on src/compiler/SourceBuilder.ts
> +			// '/* eslint @typescript-eslint/no-unused-vars: 0 */',
Not used anymore?

2021-05-13 16:17 UTC, tscpp commented on src/compiler/SourceBuilder.ts
> +	// }
Is this needed anymore?

2021-05-13 16:17 UTC, tscpp commented on src/parser/index.ts
> +export { Binding, BindingData, BindingExpression, BindingName, DiagNode, Document, Node, NodeType, ImportNode as ViewModelNode } from './bindingDOM'
Why as?

2021-05-13 20:36 UTC, maskmaster commented on src/cli/cli.ts
> +		process.exit(-1)
Changed to 2

2021-05-14 07:10 UTC, tscpp approved these changes

2021-05-14 07:12 UTC, merged